import { createStore } from 'redux';
import reducer from '../reducers/reducer';

const meals = [
  {
    key: 1,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_67caeef3c3baf61da0953ab012d1eb90',
    label: 'Rustic Garlic and Asparagus Tofu Quiche Is a Slice of Sunshine',
    image:
      'https://www.edamam.com/web-img/24b/24b65b5cbe7a3505d087eb725986c2ca.jpg',
    source: 'My Recipes',
    url:
      'http://www.myrecipes.com/recipe/rustic-garlic-and-asparagus-tofu-quiche-is-a-slice-of-sunshine',
    shareAs:
      'http://www.edamam.com/recipe/rustic-garlic-and-asparagus-tofu-quiche-is-a-slice-of-sunshine-67caeef3c3baf61da0953ab012d1eb90/vegan/vegan',
    yield: 6,
    dietLabels: [],
    healthLabels: [
      'Sugar-Conscious',
      'Vegan',
      'Vegetarian',
      'Peanut-Free',
      'Tree-Nut-Free',
      'Alcohol-Free',
    ],
    cautions: ['Soy', 'FODMAP'],
    ingredientLines: [
      '1 ¼ cups gluten-free flour blend',
      '¼ teaspoon sea salt',
      '6 tablespoons cold vegan butter',
      '3-7 tablespoons ice-cold water',
    ],
    ingredients: [],
    calories: 1267.0439999999999,
    totalWeight: 326.7473655717282,
    totalTime: 100,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 2,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_136baf8f6070d81f2e85c50cb897a7a5',
    label: 'Gwyneth Paltrow’s Life-Changing Avocado Toast',
    image:
      'https://www.edamam.com/web-img/6be/6be6b6f992498e16be5318fccd6eb760.jpg',
    source: 'The Daily Meal',
    url:
      'http://www.thedailymeal.com/recipes/gwyneth-paltrow-s-life-changing-avocado-toast-recipe',
    shareAs:
      'http://www.edamam.com/recipe/gwyneth-paltrow-s-life-changing-avocado-toast-136baf8f6070d81f2e85c50cb897a7a5/vegan/vegan',
    yield: 1,
    dietLabels: [],
    healthLabels: [
      'Sugar-Conscious',
      'Vegan',
      'Vegetarian',
      'Peanut-Free',
      'Tree-Nut-Free',
      'Alcohol-Free',
    ],
    cautions: ['Soy', 'Sulfites', 'FODMAP'],
    ingredientLines: [
      '1 slice toast',
      '1/2 ripe avocado, sliced',
      '2 Tablespoons soy-free vegan mayonnaise',
      '1/2 Teaspoon crushed red pepper flakes',
      '1 wedge lemon',
      'Kosher salt',
      'Freshly ground black pepper',
    ],
    ingredients: [],
    calories: 337.01774718756343,
    totalWeight: 162.37107291668627,
    totalTime: 0,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 3,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_119f22b168b43e59efa557a72936a9c6',
    label: 'Vegan Meringues',
    image:
      'https://www.edamam.com/web-img/160/160d1b8e395f31f81560b5fa8f4ebf6a.jpeg',
    source: 'Food Network',
    url:
      'https://www.foodnetwork.com/recipes/food-network-kitchen/vegan-meringues-3364027',
    shareAs:
      'http://www.edamam.com/recipe/vegan-meringues-119f22b168b43e59efa557a72936a9c6/vegan/vegan',
    yield: 24,
    dietLabels: ['Low-Fat'],
    healthLabels: [
      'Vegan',
      'Vegetarian',
      'Peanut-Free',
      'Tree-Nut-Free',
      'Alcohol-Free',
    ],
    cautions: ['Sulfites'],
    ingredientLines: [
      'One 15-ounce can chickpeas',
      '1/4 teaspoon cream of tartar',
      'Kosher salt',
      '3/4 cup superfine sugar',
    ],
    ingredients: [],
    calories: 1150.3025571562498,
    totalWeight: 570.7090333713063,
    totalTime: 210,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 4,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_57d9a75370c191552aed3ee73a88aca3',
    label: 'Vegan Overnight Oats',
    image:
      'https://www.edamam.com/web-img/56a/56ad06ede3f35809978dd06ecaf3d8ae.jpg',
    source: 'Oh She Glows',
    url: 'http://ohsheglows.com/2010/06/11/women-breakfast/',
    shareAs:
      'http://www.edamam.com/recipe/vegan-overnight-oats-57d9a75370c191552aed3ee73a88aca3/vegan/vegan',
    yield: 4,
    dietLabels: [],
    healthLabels: ['Vegan', 'Vegetarian', 'Peanut-Free', 'Alcohol-Free'],
    cautions: ['Gluten', 'Wheat', 'Sulfites'],
    ingredientLines: [
      '1/2 cup organic oats',
      '1.25 cups Almond Milk',
      '1 tbsp chia seeds',
      'Very tiny pinch of sea salt',
      '1/4 scoop Amazing Grass Chocolate Protein Powder',
      '1/2 tsp pure vanilla extract',
      '1 large banana, chopped or mashed',
    ],
    ingredients: [],
    calories: 577.478,
    totalWeight: 539.5016927085258,
    totalTime: 0,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 5,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_78b903c8bc3ae1bf3372495419ec550c',
    label: 'Vegan Miso Pesto',
    image:
      'https://www.edamam.com/web-img/a8c/a8cb5036c32638601affdd5729db279c.jpg',
    source: 'My Recipes',
    url: 'http://www.myrecipes.com/recipe/vegan-miso-pesto',
    shareAs:
      'http://www.edamam.com/recipe/vegan-miso-pesto-78b903c8bc3ae1bf3372495419ec550c/vegan/vegan',
    yield: 6,
    dietLabels: ['Low-Carb'],
    healthLabels: [
      'Sugar-Conscious',
      'Vegan',
      'Vegetarian',
      'Peanut-Free',
      'Alcohol-Free',
      'Immuno-Supportive',
    ],
    cautions: ['Gluten', 'Wheat', 'Sulfites'],
    ingredientLines: [
      '1/4 cup toasted pine nuts',
      '2 medium garlic cloves',
      '2 ounces fresh basil, large stems removed',
      '1/4 cup extra-virgin olive oil',
      '2 tablespoons water',
      '2 tablespoons white miso',
    ],
    ingredients: [],
    calories: 794.1382806375,
    totalWeight: 214.022575812,
    totalTime: 0,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 6,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_6825eb2ca86a81ae7f41a55889267876',
    label: 'Vegan Palak Paneer',
    image:
      'https://www.edamam.com/web-img/950/9508513fee647c150384f60d473ece2f.JPG',
    source: 'Food52',
    url: 'https://food52.com/recipes/3559-vegan-palak-paneer',
    shareAs:
      'http://www.edamam.com/recipe/vegan-palak-paneer-6825eb2ca86a81ae7f41a55889267876/vegan/vegan',
    yield: 4,
    dietLabels: [],
    healthLabels: [
      'Sugar-Conscious',
      'Vegan',
      'Vegetarian',
      'Peanut-Free',
      'Tree-Nut-Free',
      'Alcohol-Free',
      'Immuno-Supportive',
    ],
    cautions: ['Gluten', 'Wheat', 'FODMAP'],
    ingredientLines: [
      '1 tablespoon light olive or vegetable oil',
      '1 large onion, finely diced',
      '3 garlic cloves, thinly sliced',
      '1 block tofu, pressed & drained',
      '1 tablespoon garam masala',
      '2 tablespoons mustard seed',
      '2 teaspoons curry powder',
      '1 teaspoon garlic powder',
      '1 teaspoon salt',
      '1 tablespoon freshly grated ginger',
      '12 ounces frozen spinach, defrosted',
      '4 tablespoons vegetable stock',
    ],
    ingredients: [],
    calories: 610.6103686422297,
    totalWeight: 930.3334809939972,
    totalTime: 51,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 7,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_485734b928a2c64d7660056f54b80877',
    label: 'Vegan Horchata',
    image:
      'https://www.edamam.com/web-img/780/7800c7e0a545205c2ff9675e56a7e2ac.jpeg',
    source: 'Food Network',
    url: 'https://www.foodnetwork.com/recipes/vegan-horchata-3414412',
    shareAs:
      'http://www.edamam.com/recipe/vegan-horchata-485734b928a2c64d7660056f54b80877/vegan/vegan',
    yield: 8,
    dietLabels: [],
    healthLabels: ['Vegan', 'Vegetarian', 'Peanut-Free', 'Alcohol-Free'],
    cautions: ['FODMAP'],
    ingredientLines: [
      '1 1/2 cups whole raw almonds',
      '1 cup raw long-grain brown rice',
      '1/4 cup pure maple syrup',
      '1 tablespoon pure vanilla extract',
    ],
    ingredients: [],
    calories: 2171.945,
    totalWeight: 496.25,
    totalTime: 795,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 8,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_6c55b7cc933cc2975aff6ef612159bdb',
    label: 'Corn Chowder ( vegan )',
    image:
      'https://www.edamam.com/web-img/f99/f9902ca89580a38b91d6f7dc001650f2.jpg',
    source: 'Food52',
    url: 'https://food52.com/recipes/14469-corn-chowder-vegan',
    shareAs:
      'http://www.edamam.com/recipe/corn-chowder-vegan-6c55b7cc933cc2975aff6ef612159bdb/vegan/vegan',
    yield: 10,
    dietLabels: [],
    healthLabels: [
      'Vegan',
      'Vegetarian',
      'Peanut-Free',
      'Tree-Nut-Free',
      'Alcohol-Free',
    ],
    cautions: ['Tree-Nuts', 'Sulfites', 'FODMAP'],
    ingredientLines: [
      '2 quarts vegetable stock',
      '4 waxy white potatoes',
      '4 large cloves garlic',
      '1 large yellow onion',
      '1 cups coconut milk',
      '2 lbs. frozen corn',
      '1 handful fresh thyme leaves',
      '2 tablespoons extra virgin olive oil',
      '1 teaspoon cumin',
      '1 tablespoon sriracha hot sauce',
      '1 teaspoon turmeric',
      '3 tablespoons flour',
      'Salt',
      'Pepper',
      'Fresh flat-leaf parsley (for garnish)',
    ],
    ingredients: [],
    calories: 2323.7673955502955,
    totalWeight: 4109.453025976954,
    totalTime: 654,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 9,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_16e2b03dd7b2fd06cc45f704e21b6ab7',
    label: 'Vegan Summer Succotash',
    image:
      'https://www.edamam.com/web-img/3dc/3dc6e9c18e4f44d10bda2768a1f04f20.jpg',
    source: 'Food52',
    url: 'http://food52.com/recipes/23077-vegan-summer-succotash',
    shareAs:
      'http://www.edamam.com/recipe/vegan-summer-succotash-16e2b03dd7b2fd06cc45f704e21b6ab7/vegan/vegan',
    yield: 4,
    dietLabels: ['Balanced'],
    healthLabels: [
      'Vegan',
      'Vegetarian',
      'Peanut-Free',
      'Tree-Nut-Free',
      'Alcohol-Free',
    ],
    cautions: ['Tree-Nuts', 'Sulfites'],
    ingredientLines: [
      "1 1/2 cup shelled lima beans, or frozen lima beans, thawed (substitute edamame if you don't have lima beans)",
      '1 1/2 tablespoon coconut oil, divided',
      '1 small white or spring onion, diced',
      '1 shallot, minced',
      '2 cups zucchini, quartered and sliced',
      '1 cup fresh, shucked corn kernels',
      '1 cup cherry tomatoes, halved',
      'Sea salt and black pepper to taste',
      '3 tablespoons chopped fresh basil',
      '2 tablespoons chopped chives',
      '1 tablespoon lemon juice',
    ],
    ingredients: [],
    calories: 759.9219846666077,
    totalWeight: 929.8588858522307,
    totalTime: 0,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
  {
    key: 10,
    uri:
      'http://www.edamam.com/ontologies/edamam.owl#recipe_00642540ba19bb9a366523e8bfba9bd6',
    label: 'Vegan Stuffing',
    image:
      'https://www.edamam.com/web-img/758/758b66737039e1389abd83ead8a1b11d.jpeg',
    source: 'Food Network',
    url:
      'https://www.foodnetwork.com/recipes/food-network-kitchen/vegan-stuffing-3363062',
    shareAs:
      'http://www.edamam.com/recipe/vegan-stuffing-00642540ba19bb9a366523e8bfba9bd6/vegan/vegan',
    yield: 8,
    dietLabels: ['Balanced'],
    healthLabels: [
      'Vegan',
      'Vegetarian',
      'Peanut-Free',
      'Tree-Nut-Free',
      'Alcohol-Free',
    ],
    cautions: ['Sulfites', 'FODMAP'],
    ingredientLines: [
      '4 tablespoons olive oil, plus more for greasing the baking dish',
      '2 bags green tea',
      '1 large onion, chopped',
      '2 stalks celery, chopped',
      '8 ounces sliced mushrooms',
      '1 tablespoon finely chopped fresh sage',
      '1 tablespoon finely chopped fresh thyme',
      'Kosher salt and freshly ground black pepper',
      '16 cups stale, 1-inch cubed white bread (about 1 pound)',
      '1/4 cup chopped fresh parsley',
    ],
    ingredients: [],
    calories: 1851.7290764189852,
    totalWeight: 998.7759206648373,
    totalTime: 105,
    totalNutrients: {},
    totalDaily: {},
    digest: [],
  },
];

const filter = {
  searchTerm: '',
  maxCalories: 10000,
  maxTime: 1000,
  labels: {
    'Peanut-Free': false,
    'Tree-Nut-Free': false,
    'Alcohol-Free': false,
    'Sugar-Conscious': false,
    'Low-Fat': false,
    Balanced: false,
  },
};

const initialState = {
  meals,
  filter,
};

const testStore = createStore(reducer, initialState);

export default testStore;
